### ISSUE TITLE
openshift-36-metrics image missing

### ISSUE THREAD

**Issue by e-minguez** [openshift-evangelists/intro-katacoda#121]
For the using metrics scenario, the openshift-36-metrics image needs to be created.

**Comment by e-minguez** [comment]
Is there anything else I can do to speed up the image creation @BenHall ? cc @mhausenblas 
Thanks!

**Comment by BenHall** [comment]
The build is currently failing with a timeout:
```
openshift: Starting OpenShift using openshift/origin:v3.7.0 ...
    openshift: -- Checking OpenShift client ... OK
    openshift: -- Checking Docker client ... OK
    openshift: -- Checking Docker version ... OK
    openshift: -- Checking for existing OpenShift container ... OK
    openshift: -- Checking for openshift/origin:v3.7.0 image ... OK
    openshift: -- Checking Docker daemon configuration ... OK
    openshift: -- Checking for available ports ... OK
    openshift: -- Checking type of volume mount ...
    openshift:    Using nsenter mounter for OpenShift volumes
    openshift: -- Creating host directories ... OK
    openshift: -- Finding server IP ...
    openshift:    Using 127.0.0.1 as the server IP
    openshift: -- Starting OpenShift container ...
    openshift:    Creating initial OpenShift configuration
    openshift:    Starting OpenShift using container 'origin'
    openshift:    Waiting for API server to start listening
    openshift: FAIL
    openshift:    Error: timed out waiting for OpenShift container "origin"
    openshift:    WARNING: 127.0.0.1:8443 may be blocked by firewall rules
    openshift:    Details:
    openshift:      Last 10 lines of "origin" container log:
    openshift:      E0126 20:00:08.227769    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:09.853112    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:10.384951    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:11.353913    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:12.290339    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:13.300780    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:14.546959    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:15.619055    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:16.280240    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
    openshift:      E0126 20:00:17.588476    2638 controllers.go:116] Server isn't healthy yet. Waiting a little while.
```

The script is https://github.com/openshift-evangelists/intro-katacoda/tree/master/environments/openshift-3-7-clusterup

https://github.com/openshift-evangelists/intro-katacoda/blob/master/environments/openshift-3-7-clusterup/scripts/openshift.sh#L40

Any ideas why it's failing to run when inside of Packer?

**Comment by e-minguez** [comment]
Hi Ben,

The thing is, the metrics image doesn't use "oc cluster up", maybe we should follow the oc cluster up conversation in another issue. I've opened this to create the usage-metrics 3.6 image for the usage-metrics scenario -> https://github.com/openshift-evangelists/intro-katacoda/pull/109#issuecomment-358215589

Thanks.

**Comment by BenHall** [comment]
Not sure if this is an issue

```
    openshift-36-metrics: RUNNING HANDLER [openshift_metrics : restart master] ***************************
    openshift-36-metrics: fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '(openshift.master.ha is not defined or not openshift.master.ha | bool) and (not (master_service_status_changed | default(false) | bool))' failed. The error was: error while evaluating conditional ((openshift.master.ha is not defined or not openshift.master.ha | bool) and (not (master_service_status_changed | default(false) | bool))): 'dict object' has no attribute 'master'\n\nThe error appears to have been in '/root/openshift-ansible-openshift-ansible-3.6.173.0.63-1/roles/openshift_metrics/handlers/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: restart master\n  ^ here\n"}
    openshift-36-metrics:
    openshift-36-metrics: RUNNING HANDLER [openshift_metrics : restart master api] ***********************
    openshift-36-metrics:
    openshift-36-metrics: RUNNING HANDLER [openshift_metrics : restart master controllers] ***************
    openshift-36-metrics: 	to retry, use: --limit @/root/openshift-ansible-openshift-ansible-3.6.173.0.63-1/playbooks/byo/openshift-cluster/openshift-metrics.retry
    openshift-36-metrics:
    openshift-36-metrics: PLAY RECAP *********************************************************************
    openshift-36-metrics: localhost                  : ok=177  changed=44   unreachable=0    failed=1
```
